# Generated by Django 5.1.5 on 2025-02-13 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shome', '0003_gaming_software'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='software',
            new_name='Softwarez',
        ),
    ]
