# Generated by Django 5.1.5 on 2025-02-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shome', '0004_rename_software_softwarez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwarez',
            name='desc',
            field=models.CharField(max_length=3000),
        ),
    ]
