# Generated by Django 5.1.5 on 2025-02-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shome', '0005_alter_softwarez_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('subject', models.CharField(default='', max_length=50)),
                ('message', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
