# Generated by Django 5.1.5 on 2025-02-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shome', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaming',
            name='desc',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=3000),
        ),
    ]
