# Generated by Django 5.1.5 on 2025-03-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shome', '0009_blogcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
