# Generated by Django 5.1.5 on 2025-03-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shome', '0011_blogcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
