# Generated by Django 5.1.5 on 2025-03-06 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shome', '0013_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
