# Generated by Django 5.1.5 on 2025-03-06 10:46

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shome', '0015_alter_softwarez_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaming',
            name='desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
