# Generated by Django 5.1.5 on 2025-03-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shome', '0017_alter_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_header',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
