# Generated by Django 5.1.5 on 2025-03-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shome', '0018_product_product_header_alter_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaming',
            name='game_header',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='softwarez',
            name='software_header',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gaming',
            name='game_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='softwarez',
            name='software_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
